#!/bin/bash
title="System information report $LOGNAME "
CURRENT_TIME=`date +%Y%m%d`
TIME_STAMP="Generated ${CURRENT_TIME} , by ${USER}"

function report_uptime () {
	echo "<h2>System Uptime</h2>"
	echo "<PRE>$(uptime)</PRE>"
	return
}

function report_disk_space () {
	echo "<h2>System disk space</h2>"
	echo "<PRE>$(df -h)</PRE>"
	return
}

function report_home_space () {
	echo "<h2>Home disk space</h2>"
	echo "<PRE>$(du -sh ~/Downloads)</PRE>"
	return
}

echo "<HTML>"
echo "	<HEAD>"
echo "		<TITLE>${title}</TITLE>"
echo "	</HEAD>"
echo "	<BODY>"
echo "		<h1>${title}</h1>
			<P>${TIME_STAMP}</P>
			$(report_uptime)
			$(report_disk_space)
			$(report_home_space)"
echo "	</BODY>"
echo "</HTML>"
